export const COUNTRIES_DETAILS = {
  BD: {
    name: "Bangladesh",
    dialCode: "+880" as const,
    currencyCode: "BDT" as const,
    flagEmoji: "🇧🇩",
  },
  BE: {
    name: "Belgium",
    dialCode: "+32" as const,
    currencyCode: "EUR" as const,
    flagEmoji: "🇧🇪",
  },
  BF: {
    name: "Burkina Faso",
    dialCode: "+226" as const,
    currencyCode: "XOF" as const,
    flagEmoji: "🇧🇫",
  },
  BG: {
    name: "Bulgaria",
    dialCode: "+359" as const,
    currencyCode: "BGN" as const,
    flagEmoji: "🇧🇬",
  },
  BA: {
    name: "Bosnia and Herzegovina",
    dialCode: "+387" as const,
    currencyCode: "BAM" as const,
    flagEmoji: "🇧🇦",
  },
  BB: {
    name: "Barbados",
    dialCode: "+1246" as const,
    currencyCode: "BBD" as const,
    flagEmoji: "🇧🇧",
  },
  WF: {
    name: "Wallis and Futuna",
    dialCode: "+681" as const,
    currencyCode: "XPF" as const,
    flagEmoji: "🇼🇫",
  },
  BL: {
    name: "Saint Barthelemy",
    dialCode: "+590" as const,
    currencyCode: "EUR" as const,
    flagEmoji: "🇧🇱",
  },
  BM: {
    name: "Bermuda",
    dialCode: "+1441" as const,
    currencyCode: "BMD" as const,
    flagEmoji: "🇧🇲",
  },
  BN: {
    name: "Brunei Darussalam",
    dialCode: "+673" as const,
    currencyCode: "BND" as const,
    flagEmoji: "🇧🇳",
  },
  BO: {
    name: "Bolivia, Plurinational State of",
    dialCode: "+591" as const,
    currencyCode: "BOB" as const,
    flagEmoji: "🇧🇴",
  },
  BH: {
    name: "Bahrain",
    dialCode: "+973" as const,
    currencyCode: "BHD" as const,
    flagEmoji: "🇧🇭",
  },
  BI: {
    name: "Burundi",
    dialCode: "+257" as const,
    currencyCode: "BIF" as const,
    flagEmoji: "🇧🇮",
  },
  BJ: {
    name: "Benin",
    dialCode: "+229" as const,
    currencyCode: "XOF" as const,
    flagEmoji: "🇧🇯",
  },
  BT: {
    name: "Bhutan",
    dialCode: "+975" as const,
    currencyCode: "BTN" as const,
    flagEmoji: "🇧🇹",
  },
  JM: {
    name: "Jamaica",
    dialCode: "+1876" as const,
    currencyCode: "JMD" as const,
    flagEmoji: "🇯🇲",
  },
  BW: {
    name: "Botswana",
    dialCode: "+267" as const,
    currencyCode: "BWP" as const,
    flagEmoji: "🇧🇼",
  },
  WS: {
    name: "Samoa",
    dialCode: "+685" as const,
    currencyCode: "WST" as const,
    flagEmoji: "🇼🇸",
  },
  BR: {
    name: "Brazil",
    dialCode: "+55" as const,
    currencyCode: "BRL" as const,
    flagEmoji: "🇧🇷",
  },
  BS: {
    name: "Bahamas",
    dialCode: "+1242" as const,
    currencyCode: "BSD" as const,
    flagEmoji: "🇧🇸",
  },
  JE: {
    name: "Jersey",
    dialCode: "+44" as const,
    currencyCode: "GBP" as const,
    flagEmoji: "🇯🇪",
  },
  BY: {
    name: "Belarus",
    dialCode: "+375" as const,
    currencyCode: "BYR" as const,
    flagEmoji: "🇧🇾",
  },
  BZ: {
    name: "Belize",
    dialCode: "+501" as const,
    currencyCode: "BZD" as const,
    flagEmoji: "🇧🇿",
  },
  RU: {
    name: "Russia",
    dialCode: "+7" as const,
    currencyCode: "RUB" as const,
    flagEmoji: "🇷🇺",
  },
  RW: {
    name: "Rwanda",
    dialCode: "+250" as const,
    currencyCode: "RWF" as const,
    flagEmoji: "🇷🇼",
  },
  RS: {
    name: "Serbia",
    dialCode: "+381" as const,
    currencyCode: "RSD" as const,
    flagEmoji: "🇷🇸",
  },
  TL: {
    name: "Timor-Leste",
    dialCode: "+670" as const,
    currencyCode: "USD" as const,
    flagEmoji: "🇹🇱",
  },
  RE: {
    name: "Reunion",
    dialCode: "+262" as const,
    currencyCode: "EUR" as const,
    flagEmoji: "🇷🇪",
  },
  TM: {
    name: "Turkmenistan",
    dialCode: "+993" as const,
    currencyCode: "TMT" as const,
    flagEmoji: "🇹🇲",
  },
  TJ: {
    name: "Tajikistan",
    dialCode: "+992" as const,
    currencyCode: "TJS" as const,
    flagEmoji: "🇹🇯",
  },
  RO: {
    name: "Romania",
    dialCode: "+40" as const,
    currencyCode: "RON" as const,
    flagEmoji: "🇷🇴",
  },
  TK: {
    name: "Tokelau",
    dialCode: "+690" as const,
    currencyCode: "NZD" as const,
    flagEmoji: "🇹🇰",
  },
  GW: {
    name: "Guinea-Bissau",
    dialCode: "+245" as const,
    currencyCode: "XOF" as const,
    flagEmoji: "🇬🇼",
  },
  GU: {
    name: "Guam",
    dialCode: "+1671" as const,
    currencyCode: "USD" as const,
    flagEmoji: "🇬🇺",
  },
  GT: {
    name: "Guatemala",
    dialCode: "+502" as const,
    currencyCode: "GTQ" as const,
    flagEmoji: "🇬🇹",
  },
  GS: {
    name: "South Georgia and the South Sandwich Islands",
    dialCode: "+500" as const,
    currencyCode: "GBP" as const,
    flagEmoji: "🇬🇸",
  },
  GR: {
    name: "Greece",
    dialCode: "+30" as const,
    currencyCode: "EUR" as const,
    flagEmoji: "🇬🇷",
  },
  GQ: {
    name: "Equatorial Guinea",
    dialCode: "+240" as const,
    currencyCode: "XAF" as const,
    flagEmoji: "🇬🇶",
  },
  GP: {
    name: "Guadeloupe",
    dialCode: "+590" as const,
    currencyCode: "EUR" as const,
    flagEmoji: "🇬🇵",
  },
  JP: {
    name: "Japan",
    dialCode: "+81" as const,
    currencyCode: "JPY" as const,
    flagEmoji: "🇯🇵",
  },
  GY: {
    name: "Guyana",
    dialCode: "+595" as const,
    currencyCode: "GYD" as const,
    flagEmoji: "🇬🇾",
  },
  GG: {
    name: "Guernsey",
    dialCode: "+44" as const,
    currencyCode: "GBP" as const,
    flagEmoji: "🇬🇬",
  },
  GF: {
    name: "French Guiana",
    dialCode: "+594" as const,
    currencyCode: "EUR" as const,
    flagEmoji: "🇬🇫",
  },
  GE: {
    name: "Georgia",
    dialCode: "+995" as const,
    currencyCode: "GEL" as const,
    flagEmoji: "🇬🇪",
  },
  GD: {
    name: "Grenada",
    dialCode: "+1473" as const,
    currencyCode: "XCD" as const,
    flagEmoji: "🇬🇩",
  },
  GB: {
    name: "United Kingdom",
    dialCode: "+44" as const,
    currencyCode: "GBP" as const,
    flagEmoji: "🇬🇧",
  },
  GA: {
    name: "Gabon",
    dialCode: "+241" as const,
    currencyCode: "XAF" as const,
    flagEmoji: "🇬🇦",
  },
  SV: {
    name: "El Salvador",
    dialCode: "+503" as const,
    currencyCode: "USD" as const,
    flagEmoji: "🇸🇻",
  },
  GN: {
    name: "Guinea",
    dialCode: "+224" as const,
    currencyCode: "GNF" as const,
    flagEmoji: "🇬🇳",
  },
  GM: {
    name: "Gambia",
    dialCode: "+220" as const,
    currencyCode: "GMD" as const,
    flagEmoji: "🇬🇲",
  },
  GL: {
    name: "Greenland",
    dialCode: "+299" as const,
    currencyCode: "DKK" as const,
    flagEmoji: "🇬🇱",
  },
  GI: {
    name: "Gibraltar",
    dialCode: "+350" as const,
    currencyCode: "GIP" as const,
    flagEmoji: "🇬🇮",
  },
  GH: {
    name: "Ghana",
    dialCode: "+233" as const,
    currencyCode: "GHS" as const,
    flagEmoji: "🇬🇭",
  },
  OM: {
    name: "Oman",
    dialCode: "+968" as const,
    currencyCode: "OMR" as const,
    flagEmoji: "🇴🇲",
  },
  TN: {
    name: "Tunisia",
    dialCode: "+216" as const,
    currencyCode: "TND" as const,
    flagEmoji: "🇹🇳",
  },
  JO: {
    name: "Jordan",
    dialCode: "+962" as const,
    currencyCode: "JOD" as const,
    flagEmoji: "🇯🇴",
  },
  HR: {
    name: "Croatia",
    dialCode: "+385" as const,
    currencyCode: "HRK" as const,
    flagEmoji: "🇭🇷",
  },
  HT: {
    name: "Haiti",
    dialCode: "+509" as const,
    currencyCode: "HTG" as const,
    flagEmoji: "🇭🇹",
  },
  HU: {
    name: "Hungary",
    dialCode: "+36" as const,
    currencyCode: "HUF" as const,
    flagEmoji: "🇭🇺",
  },
  HK: {
    name: "Hong Kong",
    dialCode: "+852" as const,
    currencyCode: "HKD" as const,
    flagEmoji: "🇭🇰",
  },
  HN: {
    name: "Honduras",
    dialCode: "+504" as const,
    currencyCode: "HNL" as const,
    flagEmoji: "🇭🇳",
  },
  VE: {
    name: "Venezuela, Bolivarian Republic of Venezuela",
    dialCode: "+58" as const,
    currencyCode: "VEF" as const,
    flagEmoji: "🇻🇪",
  },
  PR: {
    name: "Puerto Rico",
    dialCode: "+1939" as const,
    currencyCode: "USD" as const,
    flagEmoji: "🇵🇷",
  },
  PS: {
    name: "Palestine",
    dialCode: "+970" as const,
    currencyCode: "ILS" as const,
    flagEmoji: "🇵🇸",
  },
  PW: {
    name: "Palau",
    dialCode: "+680" as const,
    currencyCode: "USD" as const,
    flagEmoji: "🇵🇼",
  },
  PT: {
    name: "Portugal",
    dialCode: "+351" as const,
    currencyCode: "EUR" as const,
    flagEmoji: "🇵🇹",
  },
  SJ: {
    name: "Svalbard and Jan Mayen",
    dialCode: "+47" as const,
    currencyCode: "NOK" as const,
    flagEmoji: "🇸🇯",
  },
  PY: {
    name: "Paraguay",
    dialCode: "+595" as const,
    currencyCode: "PYG" as const,
    flagEmoji: "🇵🇾",
  },
  IQ: {
    name: "Iraq",
    dialCode: "+964" as const,
    currencyCode: "IQD" as const,
    flagEmoji: "🇮🇶",
  },
  PA: {
    name: "Panama",
    dialCode: "+507" as const,
    currencyCode: "PAB" as const,
    flagEmoji: "🇵🇦",
  },
  PF: {
    name: "French Polynesia",
    dialCode: "+689" as const,
    currencyCode: "XPF" as const,
    flagEmoji: "🇵🇫",
  },
  PG: {
    name: "Papua New Guinea",
    dialCode: "+675" as const,
    currencyCode: "PGK" as const,
    flagEmoji: "🇵🇬",
  },
  PE: {
    name: "Peru",
    dialCode: "+51" as const,
    currencyCode: "PEN" as const,
    flagEmoji: "🇵🇪",
  },
  PK: {
    name: "Pakistan",
    dialCode: "+92" as const,
    currencyCode: "PKR" as const,
    flagEmoji: "🇵🇰",
  },
  PH: {
    name: "Philippines",
    dialCode: "+63" as const,
    currencyCode: "PHP" as const,
    flagEmoji: "🇵🇭",
  },
  PN: {
    name: "Pitcairn",
    dialCode: "+872" as const,
    currencyCode: "NZD" as const,
    flagEmoji: "🇵🇳",
  },
  PL: {
    name: "Poland",
    dialCode: "+48" as const,
    currencyCode: "PLN" as const,
    flagEmoji: "🇵🇱",
  },
  PM: {
    name: "Saint Pierre and Miquelon",
    dialCode: "+508" as const,
    currencyCode: "EUR" as const,
    flagEmoji: "🇵🇲",
  },
  ZM: {
    name: "Zambia",
    dialCode: "+260" as const,
    currencyCode: "ZMK" as const,
    flagEmoji: "🇿🇲",
  },
  EE: {
    name: "Estonia",
    dialCode: "+372" as const,
    currencyCode: "EUR" as const,
    flagEmoji: "🇪🇪",
  },
  EG: {
    name: "Egypt",
    dialCode: "+20" as const,
    currencyCode: "EGP" as const,
    flagEmoji: "🇪🇬",
  },
  ZA: {
    name: "South Africa",
    dialCode: "+27" as const,
    currencyCode: "ZAR" as const,
    flagEmoji: "🇿🇦",
  },
  EC: {
    name: "Ecuador",
    dialCode: "+593" as const,
    currencyCode: "USD" as const,
    flagEmoji: "🇪🇨",
  },
  IT: {
    name: "Italy",
    dialCode: "+39" as const,
    currencyCode: "EUR" as const,
    flagEmoji: "🇮🇹",
  },
  VN: {
    name: "Vietnam",
    dialCode: "+84" as const,
    currencyCode: "VND" as const,
    flagEmoji: "🇻🇳",
  },
  SB: {
    name: "Solomon Islands",
    dialCode: "+677" as const,
    currencyCode: "SBD" as const,
    flagEmoji: "🇸🇧",
  },
  ET: {
    name: "Ethiopia",
    dialCode: "+251" as const,
    currencyCode: "ETB" as const,
    flagEmoji: "🇪🇹",
  },
  SO: {
    name: "Somalia",
    dialCode: "+252" as const,
    currencyCode: "SOS" as const,
    flagEmoji: "🇸🇴",
  },
  ZW: {
    name: "Zimbabwe",
    dialCode: "+263" as const,
    currencyCode: "ZWL" as const,
    flagEmoji: "🇿🇼",
  },
  SA: {
    name: "Saudi Arabia",
    dialCode: "+966" as const,
    currencyCode: "SAR" as const,
    flagEmoji: "🇸🇦",
  },
  ES: {
    name: "Spain",
    dialCode: "+34" as const,
    currencyCode: "EUR" as const,
    flagEmoji: "🇪🇸",
  },
  ER: {
    name: "Eritrea",
    dialCode: "+291" as const,
    currencyCode: "ERN" as const,
    flagEmoji: "🇪🇷",
  },
  ME: {
    name: "Montenegro",
    dialCode: "+382" as const,
    currencyCode: "EUR" as const,
    flagEmoji: "🇲🇪",
  },
  MD: {
    name: "Moldova",
    dialCode: "+373" as const,
    currencyCode: "MDL" as const,
    flagEmoji: "🇲🇩",
  },
  MG: {
    name: "Madagascar",
    dialCode: "+261" as const,
    currencyCode: "MGA" as const,
    flagEmoji: "🇲🇬",
  },
  MF: {
    name: "Saint Martin",
    dialCode: "+590" as const,
    currencyCode: "EUR" as const,
    flagEmoji: "🇲🇫",
  },
  MA: {
    name: "Morocco",
    dialCode: "+212" as const,
    currencyCode: "MAD" as const,
    flagEmoji: "🇲🇦",
  },
  MC: {
    name: "Monaco",
    dialCode: "+377" as const,
    currencyCode: "EUR" as const,
    flagEmoji: "🇲🇨",
  },
  UZ: {
    name: "Uzbekistan",
    dialCode: "+998" as const,
    currencyCode: "UZS" as const,
    flagEmoji: "🇺🇿",
  },
  MM: {
    name: "Myanmar",
    dialCode: "+95" as const,
    currencyCode: "MMK" as const,
    flagEmoji: "🇲🇲",
  },
  ML: {
    name: "Mali",
    dialCode: "+223" as const,
    currencyCode: "XOF" as const,
    flagEmoji: "🇲🇱",
  },
  MO: {
    name: "Macao",
    dialCode: "+853" as const,
    currencyCode: "MOP" as const,
    flagEmoji: "🇲🇴",
  },
  MN: {
    name: "Mongolia",
    dialCode: "+976" as const,
    currencyCode: "MNT" as const,
    flagEmoji: "🇲🇳",
  },
  MH: {
    name: "Marshall Islands",
    dialCode: "+692" as const,
    currencyCode: "USD" as const,
    flagEmoji: "🇲🇭",
  },
  MK: {
    name: "Macedonia",
    dialCode: "+389" as const,
    currencyCode: "MKD" as const,
    flagEmoji: "🇲🇰",
  },
  MU: {
    name: "Mauritius",
    dialCode: "+230" as const,
    currencyCode: "MUR" as const,
    flagEmoji: "🇲🇺",
  },
  MT: {
    name: "Malta",
    dialCode: "+356" as const,
    currencyCode: "EUR" as const,
    flagEmoji: "🇲🇹",
  },
  MW: {
    name: "Malawi",
    dialCode: "+265" as const,
    currencyCode: "MWK" as const,
    flagEmoji: "🇲🇼",
  },
  MV: {
    name: "Maldives",
    dialCode: "+960" as const,
    currencyCode: "MVR" as const,
    flagEmoji: "🇲🇻",
  },
  MQ: {
    name: "Martinique",
    dialCode: "+596" as const,
    currencyCode: "EUR" as const,
    flagEmoji: "🇲🇶",
  },
  MP: {
    name: "Northern Mariana Islands",
    dialCode: "+1670" as const,
    currencyCode: "USD" as const,
    flagEmoji: "🇲🇵",
  },
  MS: {
    name: "Montserrat",
    dialCode: "+1664" as const,
    currencyCode: "XCD" as const,
    flagEmoji: "🇲🇸",
  },
  MR: {
    name: "Mauritania",
    dialCode: "+222" as const,
    currencyCode: "MRO" as const,
    flagEmoji: "🇲🇷",
  },
  IM: {
    name: "Isle of Man",
    dialCode: "+44" as const,
    currencyCode: "GBP" as const,
    flagEmoji: "🇮🇲",
  },
  UG: {
    name: "Uganda",
    dialCode: "+256" as const,
    currencyCode: "UGX" as const,
    flagEmoji: "🇺🇬",
  },
  TZ: {
    name: "Tanzania, United Republic of Tanzania",
    dialCode: "+255" as const,
    currencyCode: "TZS" as const,
    flagEmoji: "🇹🇿",
  },
  MY: {
    name: "Malaysia",
    dialCode: "+60" as const,
    currencyCode: "MYR" as const,
    flagEmoji: "🇲🇾",
  },
  MX: {
    name: "Mexico",
    dialCode: "+52" as const,
    currencyCode: "MXN" as const,
    flagEmoji: "🇲🇽",
  },
  IL: {
    name: "Israel",
    dialCode: "+972" as const,
    currencyCode: "ILS" as const,
    flagEmoji: "🇮🇱",
  },
  FR: {
    name: "France",
    dialCode: "+33" as const,
    currencyCode: "EUR" as const,
    flagEmoji: "🇫🇷",
  },
  IO: {
    name: "British Indian Ocean Territory",
    dialCode: "+246" as const,
    currencyCode: "USD" as const,
    flagEmoji: "🇮🇴",
  },
  SH: {
    name: "Saint Helena, Ascension and Tristan Da Cunha",
    dialCode: "+290" as const,
    currencyCode: "SHP" as const,
    flagEmoji: "🇸🇭",
  },
  FI: {
    name: "Finland",
    dialCode: "+358" as const,
    currencyCode: "EUR" as const,
    flagEmoji: "🇫🇮",
  },
  FJ: {
    name: "Fiji",
    dialCode: "+679" as const,
    currencyCode: "FJD" as const,
    flagEmoji: "🇫🇯",
  },
  FK: {
    name: "Falkland Islands (Malvinas)",
    dialCode: "+500" as const,
    currencyCode: "FKP" as const,
    flagEmoji: "🇫🇰",
  },
  FM: {
    name: "Micronesia, Federated States of Micronesia",
    dialCode: "+691" as const,
    currencyCode: "USD" as const,
    flagEmoji: "🇫🇲",
  },
  FO: {
    name: "Faroe Islands",
    dialCode: "+298" as const,
    currencyCode: "DKK" as const,
    flagEmoji: "🇫🇴",
  },
  NI: {
    name: "Nicaragua",
    dialCode: "+505" as const,
    currencyCode: "NIO" as const,
    flagEmoji: "🇳🇮",
  },
  NL: {
    name: "Netherlands",
    dialCode: "+31" as const,
    currencyCode: "EUR" as const,
    flagEmoji: "🇳🇱",
  },
  NO: {
    name: "Norway",
    dialCode: "+47" as const,
    currencyCode: "NOK" as const,
    flagEmoji: "🇳🇴",
  },
  NA: {
    name: "Namibia",
    dialCode: "+264" as const,
    currencyCode: "NAD" as const,
    flagEmoji: "🇳🇦",
  },
  VU: {
    name: "Vanuatu",
    dialCode: "+678" as const,
    currencyCode: "VUV" as const,
    flagEmoji: "🇻🇺",
  },
  NC: {
    name: "New Caledonia",
    dialCode: "+687" as const,
    currencyCode: "XPF" as const,
    flagEmoji: "🇳🇨",
  },
  NE: {
    name: "Niger",
    dialCode: "+227" as const,
    currencyCode: "XOF" as const,
    flagEmoji: "🇳🇪",
  },
  NF: {
    name: "Norfolk Island",
    dialCode: "+672" as const,
    currencyCode: "AUD" as const,
    flagEmoji: "🇳🇫",
  },
  NG: {
    name: "Nigeria",
    dialCode: "+234" as const,
    currencyCode: "NGN" as const,
    flagEmoji: "🇳🇬",
  },
  NZ: {
    name: "New Zealand",
    dialCode: "+64" as const,
    currencyCode: "NZD" as const,
    flagEmoji: "🇳🇿",
  },
  NP: {
    name: "Nepal",
    dialCode: "+977" as const,
    currencyCode: "NPR" as const,
    flagEmoji: "🇳🇵",
  },
  NR: {
    name: "Nauru",
    dialCode: "+674" as const,
    currencyCode: "AUD" as const,
    flagEmoji: "🇳🇷",
  },
  NU: {
    name: "Niue",
    dialCode: "+683" as const,
    currencyCode: "NZD" as const,
    flagEmoji: "🇳🇺",
  },
  CK: {
    name: "Cook Islands",
    dialCode: "+682" as const,
    currencyCode: "NZD" as const,
    flagEmoji: "🇨🇰",
  },
  CI: {
    name: "Cote d'Ivoire",
    dialCode: "+225" as const,
    currencyCode: "XOF" as const,
    flagEmoji: "🇨🇮",
  },
  CH: {
    name: "Switzerland",
    dialCode: "+41" as const,
    currencyCode: "CHF" as const,
    flagEmoji: "🇨🇭",
  },
  CO: {
    name: "Colombia",
    dialCode: "+57" as const,
    currencyCode: "COP" as const,
    flagEmoji: "🇨🇴",
  },
  CN: {
    name: "China",
    dialCode: "+86" as const,
    currencyCode: "CNY" as const,
    flagEmoji: "🇨🇳",
  },
  CM: {
    name: "Cameroon",
    dialCode: "+237" as const,
    currencyCode: "XAF" as const,
    flagEmoji: "🇨🇲",
  },
  CL: {
    name: "Chile",
    dialCode: "+56" as const,
    currencyCode: "CLP" as const,
    flagEmoji: "🇨🇱",
  },
  CC: {
    name: "Cocos (Keeling) Islands",
    dialCode: "+61" as const,
    currencyCode: "AUD" as const,
    flagEmoji: "🇨🇨",
  },
  CA: {
    name: "Canada",
    dialCode: "+1" as const,
    currencyCode: "CAD" as const,
    flagEmoji: "🇨🇦",
  },
  CG: {
    name: "Congo",
    dialCode: "+242" as const,
    currencyCode: "XAF" as const,
    flagEmoji: "🇨🇬",
  },
  CF: {
    name: "Central African Republic",
    dialCode: "+236" as const,
    currencyCode: "XAF" as const,
    flagEmoji: "🇨🇫",
  },
  CD: {
    name: "Congo, The Democratic Republic of the Congo",
    dialCode: "+243" as const,
    currencyCode: "CDF" as const,
    flagEmoji: "🇨🇩",
  },
  CZ: {
    name: "Czech Republic",
    dialCode: "+420" as const,
    currencyCode: "CZK" as const,
    flagEmoji: "🇨🇿",
  },
  CY: {
    name: "Cyprus",
    dialCode: "+357" as const,
    currencyCode: "EUR" as const,
    flagEmoji: "🇨🇾",
  },
  CX: {
    name: "Christmas Island",
    dialCode: "+61" as const,
    currencyCode: "AUD" as const,
    flagEmoji: "🇨🇽",
  },
  CR: {
    name: "Costa Rica",
    dialCode: "+506" as const,
    currencyCode: "CRC" as const,
    flagEmoji: "🇨🇷",
  },
  CV: {
    name: "Cape Verde",
    dialCode: "+238" as const,
    currencyCode: "CVE" as const,
    flagEmoji: "🇨🇻",
  },
  CU: {
    name: "Cuba",
    dialCode: "+53" as const,
    currencyCode: "CUP" as const,
    flagEmoji: "🇨🇺",
  },
  SZ: {
    name: "Swaziland",
    dialCode: "+268" as const,
    currencyCode: "SZL" as const,
    flagEmoji: "🇸🇿",
  },
  SY: {
    name: "Syrian Arab Republic",
    dialCode: "+963" as const,
    currencyCode: "SYP" as const,
    flagEmoji: "🇸🇾",
  },
  KG: {
    name: "Kyrgyzstan",
    dialCode: "+996" as const,
    currencyCode: "KGS" as const,
    flagEmoji: "🇰🇬",
  },
  KE: {
    name: "Kenya",
    dialCode: "+254" as const,
    currencyCode: "KES" as const,
    flagEmoji: "🇰🇪",
  },
  SS: {
    name: "South Sudan",
    dialCode: "+211" as const,
    currencyCode: "SSP" as const,
    flagEmoji: "🇸🇸",
  },
  SR: {
    name: "Suriname",
    dialCode: "+597" as const,
    currencyCode: "SRD" as const,
    flagEmoji: "🇸🇷",
  },
  KI: {
    name: "Kiribati",
    dialCode: "+686" as const,
    currencyCode: "AUD" as const,
    flagEmoji: "🇰🇮",
  },
  KH: {
    name: "Cambodia",
    dialCode: "+855" as const,
    currencyCode: "KHR" as const,
    flagEmoji: "🇰🇭",
  },
  KN: {
    name: "Saint Kitts and Nevis",
    dialCode: "+1869" as const,
    currencyCode: "XCD" as const,
    flagEmoji: "🇰🇳",
  },
  KM: {
    name: "Comoros",
    dialCode: "+269" as const,
    currencyCode: "KMF" as const,
    flagEmoji: "🇰🇲",
  },
  ST: {
    name: "Sao Tome and Principe",
    dialCode: "+239" as const,
    currencyCode: "STD" as const,
    flagEmoji: "🇸🇹",
  },
  SK: {
    name: "Slovakia",
    dialCode: "+421" as const,
    currencyCode: "EUR" as const,
    flagEmoji: "🇸🇰",
  },
  KR: {
    name: "Korea, Republic of South Korea",
    dialCode: "+82" as const,
    currencyCode: "KRW" as const,
    flagEmoji: "🇰🇷",
  },
  SI: {
    name: "Slovenia",
    dialCode: "+386" as const,
    currencyCode: "EUR" as const,
    flagEmoji: "🇸🇮",
  },
  KP: {
    name: "Korea, Democratic People's Republic of Korea",
    dialCode: "+850" as const,
    currencyCode: "KPW" as const,
    flagEmoji: "🇰🇵",
  },
  KW: {
    name: "Kuwait",
    dialCode: "+965" as const,
    currencyCode: "KWD" as const,
    flagEmoji: "🇰🇼",
  },
  SN: {
    name: "Senegal",
    dialCode: "+221" as const,
    currencyCode: "XOF" as const,
    flagEmoji: "🇸🇳",
  },
  SM: {
    name: "San Marino",
    dialCode: "+378" as const,
    currencyCode: "EUR" as const,
    flagEmoji: "🇸🇲",
  },
  SL: {
    name: "Sierra Leone",
    dialCode: "+232" as const,
    currencyCode: "SLL" as const,
    flagEmoji: "🇸🇱",
  },
  SC: {
    name: "Seychelles",
    dialCode: "+248" as const,
    currencyCode: "SCR" as const,
    flagEmoji: "🇸🇨",
  },
  KZ: {
    name: "Kazakhstan",
    dialCode: "+77" as const,
    currencyCode: "KZT" as const,
    flagEmoji: "🇰🇿",
  },
  KY: {
    name: "Cayman Islands",
    dialCode: "+ 345" as const,
    currencyCode: "KYD" as const,
    flagEmoji: "🇰🇾",
  },
  SG: {
    name: "Singapore",
    dialCode: "+65" as const,
    currencyCode: "SGD" as const,
    flagEmoji: "🇸🇬",
  },
  SE: {
    name: "Sweden",
    dialCode: "+46" as const,
    currencyCode: "SEK" as const,
    flagEmoji: "🇸🇪",
  },
  SD: {
    name: "Sudan",
    dialCode: "+249" as const,
    currencyCode: "SDG" as const,
    flagEmoji: "🇸🇩",
  },
  DO: {
    name: "Dominican Republic",
    dialCode: "+1849" as const,
    currencyCode: "DOP" as const,
    flagEmoji: "🇩🇴",
  },
  DM: {
    name: "Dominica",
    dialCode: "+1767" as const,
    currencyCode: "XCD" as const,
    flagEmoji: "🇩🇲",
  },
  DJ: {
    name: "Djibouti",
    dialCode: "+253" as const,
    currencyCode: "DJF" as const,
    flagEmoji: "🇩🇯",
  },
  DK: {
    name: "Denmark",
    dialCode: "+45" as const,
    currencyCode: "DKK" as const,
    flagEmoji: "🇩🇰",
  },
  VG: {
    name: "Virgin Islands, British",
    dialCode: "+1284" as const,
    currencyCode: "USD" as const,
    flagEmoji: "🇻🇬",
  },
  DE: {
    name: "Germany",
    dialCode: "+49" as const,
    currencyCode: "EUR" as const,
    flagEmoji: "🇩🇪",
  },
  YE: {
    name: "Yemen",
    dialCode: "+967" as const,
    currencyCode: "YER" as const,
    flagEmoji: "🇾🇪",
  },
  DZ: {
    name: "Algeria",
    dialCode: "+213" as const,
    currencyCode: "DZD" as const,
    flagEmoji: "🇩🇿",
  },
  US: {
    name: "United States",
    dialCode: "+1" as const,
    currencyCode: "USD" as const,
    flagEmoji: "🇺🇸",
  },
  UY: {
    name: "Uruguay",
    dialCode: "+598" as const,
    currencyCode: "UYU" as const,
    flagEmoji: "🇺🇾",
  },
  YT: {
    name: "Mayotte",
    dialCode: "+262" as const,
    currencyCode: "EUR" as const,
    flagEmoji: "🇾🇹",
  },
  LB: {
    name: "Lebanon",
    dialCode: "+961" as const,
    currencyCode: "LBP" as const,
    flagEmoji: "🇱🇧",
  },
  LC: {
    name: "Saint Lucia",
    dialCode: "+1758" as const,
    currencyCode: "XCD" as const,
    flagEmoji: "🇱🇨",
  },
  LA: {
    name: "Laos",
    dialCode: "+856" as const,
    currencyCode: "LAK" as const,
    flagEmoji: "🇱🇦",
  },
  TV: {
    name: "Tuvalu",
    dialCode: "+688" as const,
    currencyCode: "AUD" as const,
    flagEmoji: "🇹🇻",
  },
  TW: {
    name: "Taiwan",
    dialCode: "+886" as const,
    currencyCode: "TWD" as const,
    flagEmoji: "🇹🇼",
  },
  TT: {
    name: "Trinidad and Tobago",
    dialCode: "+1868" as const,
    currencyCode: "TTD" as const,
    flagEmoji: "🇹🇹",
  },
  TR: {
    name: "Turkey",
    dialCode: "+90" as const,
    currencyCode: "TRY" as const,
    flagEmoji: "🇹🇷",
  },
  LK: {
    name: "Sri Lanka",
    dialCode: "+94" as const,
    currencyCode: "LKR" as const,
    flagEmoji: "🇱🇰",
  },
  LI: {
    name: "Liechtenstein",
    dialCode: "+423" as const,
    currencyCode: "CHF" as const,
    flagEmoji: "🇱🇮",
  },
  LV: {
    name: "Latvia",
    dialCode: "+371" as const,
    currencyCode: "EUR" as const,
    flagEmoji: "🇱🇻",
  },
  TO: {
    name: "Tonga",
    dialCode: "+676" as const,
    currencyCode: "TOP" as const,
    flagEmoji: "🇹🇴",
  },
  LT: {
    name: "Lithuania",
    dialCode: "+370" as const,
    currencyCode: "LTL" as const,
    flagEmoji: "🇱🇹",
  },
  LU: {
    name: "Luxembourg",
    dialCode: "+352" as const,
    currencyCode: "EUR" as const,
    flagEmoji: "🇱🇺",
  },
  LR: {
    name: "Liberia",
    dialCode: "+231" as const,
    currencyCode: "LRD" as const,
    flagEmoji: "🇱🇷",
  },
  LS: {
    name: "Lesotho",
    dialCode: "+266" as const,
    currencyCode: "LSL" as const,
    flagEmoji: "🇱🇸",
  },
  TH: {
    name: "Thailand",
    dialCode: "+66" as const,
    currencyCode: "THB" as const,
    flagEmoji: "🇹🇭",
  },
  TG: {
    name: "Togo",
    dialCode: "+228" as const,
    currencyCode: "XOF" as const,
    flagEmoji: "🇹🇬",
  },
  TD: {
    name: "Chad",
    dialCode: "+235" as const,
    currencyCode: "XAF" as const,
    flagEmoji: "🇹🇩",
  },
  TC: {
    name: "Turks and Caicos Islands",
    dialCode: "+1649" as const,
    currencyCode: "USD" as const,
    flagEmoji: "🇹🇨",
  },
  LY: {
    name: "Libyan Arab Jamahiriya",
    dialCode: "+218" as const,
    currencyCode: "LYD" as const,
    flagEmoji: "🇱🇾",
  },
  VA: {
    name: "Holy See (Vatican City State)",
    dialCode: "+379" as const,
    currencyCode: "EUR" as const,
    flagEmoji: "🇻🇦",
  },
  VC: {
    name: "Saint Vincent and the Grenadines",
    dialCode: "+1784" as const,
    currencyCode: "XCD" as const,
    flagEmoji: "🇻🇨",
  },
  AE: {
    name: "United Arab Emirates",
    dialCode: "+971" as const,
    currencyCode: "AED" as const,
    flagEmoji: "🇦🇪",
  },
  AD: {
    name: "Andorra",
    dialCode: "+376" as const,
    currencyCode: "EUR" as const,
    flagEmoji: "🇦🇩",
  },
  AG: {
    name: "Antigua and Barbuda",
    dialCode: "+1268" as const,
    currencyCode: "XCD" as const,
    flagEmoji: "🇦🇬",
  },
  AF: {
    name: "Afghanistan",
    dialCode: "+93" as const,
    currencyCode: "AFN" as const,
    flagEmoji: "🇦🇫",
  },
  AI: {
    name: "Anguilla",
    dialCode: "+1264" as const,
    currencyCode: "XCD" as const,
    flagEmoji: "🇦🇮",
  },
  VI: {
    name: "Virgin Islands, U.S.",
    dialCode: "+1340" as const,
    currencyCode: "USD" as const,
    flagEmoji: "🇻🇮",
  },
  IS: {
    name: "Iceland",
    dialCode: "+354" as const,
    currencyCode: "ISK" as const,
    flagEmoji: "🇮🇸",
  },
  IR: {
    name: "Iran, Islamic Republic of Persian Gulf",
    dialCode: "+98" as const,
    currencyCode: "IRR" as const,
    flagEmoji: "🇮🇷",
  },
  AM: {
    name: "Armenia",
    dialCode: "+374" as const,
    currencyCode: "AMD" as const,
    flagEmoji: "🇦🇲",
  },
  AL: {
    name: "Albania",
    dialCode: "+355" as const,
    currencyCode: "ALL" as const,
    flagEmoji: "🇦🇱",
  },
  AO: {
    name: "Angola",
    dialCode: "+244" as const,
    currencyCode: "AOA" as const,
    flagEmoji: "🇦🇴",
  },
  AQ: {
    name: "Antarctica",
    dialCode: "+672" as const,
    currencyCode: "XCD" as const,
    flagEmoji: "🇦🇶",
  },
  AS: {
    name: "AmericanSamoa",
    dialCode: "+1684" as const,
    currencyCode: "USD" as const,
    flagEmoji: "🇦🇸",
  },
  AR: {
    name: "Argentina",
    dialCode: "+54" as const,
    currencyCode: "ARS" as const,
    flagEmoji: "🇦🇷",
  },
  AU: {
    name: "Australia",
    dialCode: "+61" as const,
    currencyCode: "AUD" as const,
    flagEmoji: "🇦🇺",
  },
  AT: {
    name: "Austria",
    dialCode: "+43" as const,
    currencyCode: "EUR" as const,
    flagEmoji: "🇦🇹",
  },
  AW: {
    name: "Aruba",
    dialCode: "+297" as const,
    currencyCode: "AWG" as const,
    flagEmoji: "🇦🇼",
  },
  IN: {
    name: "India",
    dialCode: "+91" as const,
    currencyCode: "INR" as const,
    flagEmoji: "🇮🇳",
  },
  AX: {
    name: "Aland Islands",
    dialCode: "+358" as const,
    currencyCode: "EUR" as const,
    flagEmoji: "🇦🇽",
  },
  AZ: {
    name: "Azerbaijan",
    dialCode: "+994" as const,
    currencyCode: "AZN" as const,
    flagEmoji: "🇦🇿",
  },
  IE: {
    name: "Ireland",
    dialCode: "+353" as const,
    currencyCode: "EUR" as const,
    flagEmoji: "🇮🇪",
  },
  ID: {
    name: "Indonesia",
    dialCode: "+62" as const,
    currencyCode: "IDR" as const,
    flagEmoji: "🇮🇩",
  },
  UA: {
    name: "Ukraine",
    dialCode: "+380" as const,
    currencyCode: "UAH" as const,
    flagEmoji: "🇺🇦",
  },
  QA: {
    name: "Qatar",
    dialCode: "+974" as const,
    currencyCode: "QAR" as const,
    flagEmoji: "🇶🇦",
  },
  MZ: {
    name: "Mozambique",
    dialCode: "+258" as const,
    currencyCode: "MZN" as const,
    flagEmoji: "🇲🇿",
  },
};

export type TCountryCode = keyof typeof COUNTRIES_DETAILS;
export type TDialCode = (typeof COUNTRIES_DETAILS)[TCountryCode]["dialCode"];
export type TCurrencyCode =
  (typeof COUNTRIES_DETAILS)[TCountryCode]["currencyCode"];

const countryCodes = Object.keys(COUNTRIES_DETAILS) as TCountryCode[];

export type TCountryDetails = {
  name: string;
  dialCode: TDialCode;
  currencyCode: TCurrencyCode;
  flagEmoji: string;
};

export type TCountryData = TCountryDetails & {
  countryCode: TCountryCode;
};

export const COUNTRIES_DATA: {
  countryCode: TCountryCode;
  name: string;
  dialCode: TDialCode;
  currencyCode: TCurrencyCode;
  flagEmoji: string;
}[] = countryCodes
  .map((countryCode: TCountryCode) => ({
    countryCode,
    name: COUNTRIES_DETAILS[countryCode].name as string,
    dialCode: COUNTRIES_DETAILS[countryCode].dialCode as TDialCode,
    currencyCode: COUNTRIES_DETAILS[countryCode].currencyCode as TCurrencyCode,
    flagEmoji: COUNTRIES_DETAILS[countryCode].flagEmoji as string,
  }))
  .sort((a, b) => a.name.localeCompare(b.name));

export const countryNames = COUNTRIES_DATA.map((c) => c.name) as string[];
export const dialCodes = COUNTRIES_DATA.map((c) => c.dialCode) as TDialCode[];
export const currencyCodes = COUNTRIES_DATA.map(
  (c) => c.currencyCode
) as TCurrencyCode[];
export const countryFlags = COUNTRIES_DATA.map((c) => c.flagEmoji) as string[];
